### ISSUE TITLE
unable to remove the plugin from the powertoys run page

### ISSUE THREAD

**Issue by AfzalArfan** [waaverecords/PowerToys-Run-Spotify#11]
after working for many days on how to run it. i am fed up & that this is affecting my windows start up time, so i want to remove it from the power toys  run menu but there is only one option to turn it of or on, if i try to remove it from the plugins folder it give me a window that it failed to load the plugin. how do i resolve it.

idk why it is not working on my pc i really want thins to function but this plugin isn't responding. i am basically trying to re-install this on the power toy but it doesn't go off the power toy run menu.

**Comment by waaverecords** [comment]
1. Close PowerToys.
2. Go to the PowerToys Run plugin folder.
3. Delete the PowerToys-Run-Spotify folder.

That's it.

If you still encounter issues after this, then the problem lies elsewhere.

You can also look at logs to know what's going on.

`%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs`
