### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by harsharora08** [waaverecords/PowerToys-Run-Spotify#26]
PowerToys version: 0.81.0
Plugin version: 0.81.0

I have tried a complete reinstall of the plugin but I can't get it to work. It doesn't ask for a login, I think that is the issue.

Screenshot:
![image](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/41362690/5ba8c428-163b-4a97-a84c-9fe50b5abdb5)

Any fixes?
Thanks

**Comment by waaverecords** [comment]
What's the issue? Your screenshot shows normal behavior.
Perhaps with searching for songs?

**Comment by waaverecords** [comment]
Spotify Premium is required. It won't work otherwise.

You can do the following if you do have Premium:
- check that the `Client ID` set in the PowerToys Run section is the right one
- prompt the login again by going to `%localAppData%\PowerToys-Run-Spotify` and deleting the `credentials.json file`
- check the logs (`%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs`) for further info on what's going wrong
